#!/bin/bash

# ./devtools command <no-stdin-stdout> <stdin-only> <stdout-only> <both-stdin-stdout> $*

# read link of dotfiles, and list up mount files...
mounts=
for i in $(find $HOME -type l -maxdepth 1); do
  mounts="$mounts -v $(readlink $i):/root/$(basename $i)"
done

# if input is via pipe, use only -i
# else use -it
cmd=$1
a=$2
b=$3
c=$4
d=$5
shift 5
it=
if [ -p /dev/stdin -a -p /dev/stdout ]; then
  it=$d
elif [ -p /dev/stdin ]; then
  it=$b
elif [ -p /dev/stdout ]; then
  it=$c
else
  it=$a
fi

docker run --rm -v /:/host $mounts $it devtools /bin/bash -c "cd /host$(pwd) && $cmd $*"
