#!/bin/bash

# ./devtools \
#     docker \
#     dockerarg \
#     command \
#     no-stdin-stdout \
#     stdin-only \
#     stdout-only \
#     both-stdin-stdout \
#     "$@"

# read link of dotfiles, and list up mount files...
mounts=
for i in $(find $HOME -name '.*' -maxdepth 1); do
  if [ -L $i ]; then
    mounts="$mounts -v $(readlink $i):/root/$(basename $i)"
  else
    mounts="$mounts -v $i:/root/$(basename $i)"
  fi
done

# if input is via pipe, use only -i
# else use -it
docker=$1
dockerarg=$2
cmd=$3
a=$4
b=$5
c=$6
d=$7
shift 7
it=
if [ -p /dev/stdin -a -p /dev/stdout ]; then
  it=$d
elif [ -p /dev/stdin ]; then
  it=$b
elif [ -p /dev/stdout ]; then
  it=$c
else
  it=$a
fi

case "$docker" in
    docker )
        docker \
            run \
            $dockerarg \
            --rm -v /:/host $mounts \
            -w "/host$(pwd)" \
            $it \
            devtools $cmd "$@" ;;
    docker-compose )
        docker-compose \
            -f $HOME/bin/docker-compose.yml \
            run \
            $dockerarg \
            $mounts \
            -w "/nfshost$(pwd)" \
            devtools $cmd "$@" ;;
    * )
        echo "invalid" >> /dev/stderr
esac
